[package]
name = "subxt-macro"
version = "0.27.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
publish = true
autotests = false

license = "Apache-2.0 OR GPL-3.0"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt"
homepage = "https://www.parity.io/"
description = "Generate types and helpers for interacting with Substrate runtimes."

[lib]
proc-macro = true

[dependencies]
darling = "0.14.3"
proc-macro-error = "1.0.4"
syn = "1.0.109"

subxt-codegen = { path = "../codegen", version = "0.27.1" }
