[package]
name = "subxt-examples"
version = "0.27.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
publish = false

license = "Apache-2.0 OR GPL-3.0"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt"
homepage = "https://www.parity.io/"
description = "Subxt example usage"

[dev-dependencies]
subxt = { path = "../subxt" }
tokio = { version = "1.25", features = ["rt-multi-thread", "macros", "time"] }
sp-keyring = "18.0.0"
futures = "0.3.26"
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
hex = "0.4.3"
tracing-subscriber = "0.3.11"
sp-core = { version = "16.0.0", default-features = false }
sp-runtime = "18.0.0"
